### PR TITLE
Add note to rsct doc for memory limit

### PR DESCRIPTION
**Pull request by juliemathew**
Signed-off-by: mjulie <mjulie@in.ibm.com>

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by neikei** [comment]
@juliemathew, what does large memory configuration mean? It would be great if you could share your experiences with us, because our largest worker are configured with ~200GB memory.

**Comment by juliemathew** [comment]
> 
> 
> @juliemathew, what does large memory configuration mean? It would be great if you could share your experiences with us, because our largest worker are configured with ~200GB memory.

@neikei 
We deployed an OCP 4.8 cluster with large config, in order to execute scale tests. One of the worker nodes is configured with 2 TB RAM, 64 cores.

powervm-rmc pod crashed on this worker node with the following error message. 
On modifying the memory limit from 1 Gi to 2Gi, the pod started  running fine.

```
Containers:
  powervm-rmc:
    Container ID:   cri-o://de9e9175049665f87e054c3a64cf873a34790cc9f8be829e470507ba2896b2d3
    Image:          quay.io/powercloud/rsct-ppc64le:latest
    Image ID:       quay.io/powercloud/rsct-ppc64le@sha256:2bd63f8e18ed1642e36897eeef7992c307552c1107dff215a3f1817873e88a1f
    Ports:          657/TCP, 657/UDP
    Host Ports:     657/TCP, 657/UDP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```

**Review by Prajyot-Parab — COMMENTED** [review]
/approve

**Review by Prajyot-Parab — APPROVED** [review]

**Pull request merged**
