### PR TITLE
Create OWNERS

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Creating this as per comment https://github.com/ocp-power-automation/ocp4-playbooks/pull/138#issuecomment-931022630

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
/lgtm

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag we might need to give `admin` access for bot to this repo for plugins like `/lgtm` and `/approve` to work.

**Comment by mkumatag** [comment]
> @mkumatag we might need to give `admin` access for bot to this repo for plugins like `/lgtm` and `/approve` to work.

I just added the required team to this repo,!

**Pull request merged**
