### PR TITLE
Add missing filesystem for chrony.conf

### LINKED ISSUE #127: update_ignition_bootstrap.py is missing filesystem stanza for chrony.conf entry
Missing " 'filesystem': 'root',  'path': '/etc/chrony.conf' " could cause OCP installation fail on ignition process.

### PR DESCRIPTION
**Pull request by cs-zhang**
Fixed: #127 

Signed-off-by: CS Zhang <zhangcho@us.ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
@cs-zhang ignition spec v3 does not have filesystem attribute, this will fail. What is the intention here?

**Comment by cs-zhang** [comment]
Currently I am help a team to install OCP 4.5, the bootstrap failed to process the ignition file:
```
Jun 22 22:23:03 localhost ignition[865]: error at line 1, column 294812
                                         no filesystem specified
Jun 22 22:23:03 localhost ignition[865]: failed to fetch config: config is not valid
```
Do you means adding `filesystem` could cause the newer OCP installation fail? But other files in ignition still using `filesystem`.

**Comment by yussufsh** [comment]
> Do you means adding `filesystem` could cause the newer OCP installation fail? But other files in ignition still using `filesystem`.

You need to use `release-4.5` branch which uses ignition spec v2 and has filesystem set as 'root'. Both powervm and powervs repos have these branches pointing to the latest hash of this branch.

You know this was the main reason to branch out the versions in these projects.

I am going to close this PR. Suggest you to follow the branch release-4.5 to install OCP 4.5, this is documented. We have our CI as well running this version.

**Pull request closed without merging**
