### PR TITLE
adding ack for 4.13 to 4.14 upgrades

### LINKED ISSUE #189: Playbook run successfully but cluster is not upgraded to next required version.
**Upgrade from 4.13.13 -> 4.14.0-rc.2 in Disconnected environment:**

var.tfvars:

```
rhel_image_name  = "rhel-92-05032023-tier1"
rhcos_image_name = "rhcos-413-92-tier1"

openshift_install_tarball = "https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.13.13/openshift-install-linux.tar.gz"
openshift_client_tarball  = "https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.13.13/openshift-client-linux.tar.gz"

enable_local_registry      = true  #Set to true to enable usage of local registry for restricted network install.
local_registry_image       = "docker.io/ibmcom/registry-ppc64le:2.6.2.5"
ocp_release_tag            = "4.13.13-ppc64le"
ocp_release_name           = "ocp-release"

setup_squid_proxy          = false
proxy                      = {server = ""}
setup_snat                 = false
```

Cluster output:
```
Outputs:

bastion_private_ip = "193.168.200.148"
bastion_public_ip = "158.176.147.149"
bastion_ssh_command = "ssh -i /root/data/id_rsa root@158.176.147.149"
bootstrap_ip = "193.168.200.100"
cluster_authentication_details = "Cluster authentication details are available in 158.176.147.149 under ~/openstack-upi/auth"
cluster_id = "rdr-shu-dis"
dns_entries = <<EOT

api.rdr-shu-dis.ibm.com.  IN  A  158.176.147.149
*.apps.rdr-shu-dis.ibm.com.  IN  A  158.176.147.149

EOT
etc_hosts_entries = <<EOT

158.176.147.149 api.rdr-shu-dis.ibm.com console-openshift-console.apps.rdr-shu-dis.ibm.com integrated-oauth-server-openshift-authentication.apps.rdr-shu-dis.ibm.com oauth-openshift.apps.rdr-shu-dis.ibm.com prometheus-k8s-openshift-monitoring.apps.rdr-shu-dis.ibm.com grafana-openshift-monitoring.apps.rdr-shu-dis.ibm.com example.apps.rdr-shu-dis.ibm.com

EOT
install_status = "COMPLETED"
master_ips = [
  "193.168.200.77",
  "193.168.200.75",
  "193.168.200.41",
]
name_prefix = "rdr-shu-dis-lon06-"
oc_server_url = "https://api.rdr-shu-dis.ibm.com:6443"
storageclass_name = "nfs-storage-provisioner"
web_console_url = "https://console-openshift-console.apps.rdr-shu-dis.ibm.com"
worker_ips = [
  "193.168.200.138",
  "193.168.200.141",
]
```

**Basic CLI check on cluster:**
```
[root@rdr-shu-dis-lon06-bastion-0 ~]# oc version
Client Version: 4.13.13
Kustomize Version: v4.5.7
Server Version: 4.13.13
Kubernetes Version: v1.26.7+c7ee51f

[root@rdr-shu-dis-lon06-bastion-0 ~]# oc get nodes
NAME                                 STATUS   ROLES                  AGE   VERSION
lon06-master-0.rdr-shu-dis.ibm.com   Ready    control-plane,master   43m   v1.26.7+c7ee51f
lon06-master-1.rdr-shu-dis.ibm.com   Ready    control-plane,master   43m   v1.26.7+c7ee51f
lon06-master-2.rdr-shu-dis.ibm.com   Ready    control-plane,master   43m   v1.26.7+c7ee51f
lon06-worker-0.rdr-shu-dis.ibm.com   Ready    worker                 24m   v1.26.7+c7ee51f
lon06-worker-1.rdr-shu-dis.ibm.com   Ready    worker                 25m   v1.26.7+c7ee51f

[root@rdr-shu-dis-lon06-bastion-0 ~]# oc adm top nodes
NAME                                 CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
lon06-master-0.rdr-shu-dis.ibm.com   897m         11%    6158Mi          19%
lon06-master-1.rdr-shu-dis.ibm.com   744m         9%     6196Mi          19%
lon06-master-2.rdr-shu-dis.ibm.com   922m         12%    7785Mi          24%
lon06-worker-0.rdr-shu-dis.ibm.com   633m         8%     5153Mi          16%
lon06-worker-1.rdr-shu-dis.ibm.com   369m         4%     5843Mi          18%

[root@rdr-shu-dis-lon06-bastion-0 ~]# oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.13.13   True        False         False      15m
baremetal                                  4.13.13   True        False         False      39m
cloud-controller-manager                   4.13.13   True        False         False      41m
cloud-credential                           4.13.13   True        False         False      51m
cluster-autoscaler                         4.13.13   True        False         False      38m
config-operator                            4.13.13   True        False         False      40m
console                                    4.13.13   True        False         False      20m
control-plane-machine-set                  4.13.13   True        False         False      38m
csi-snapshot-controller                    4.13.13   True        False         False      39m
dns                                        4.13.13   True        False         False      38m
etcd                                       4.13.13   True        False         False      38m
image-registry                             4.13.13   True        False         False      14m
ingress                                    4.13.13   True        False         False      24m
insights                                   4.13.13   True        False         False      33m
kube-apiserver                             4.13.13   True        False         False      31m
kube-controller-manager                    4.13.13   True        False         False      36m
kube-scheduler                             4.13.13   True        False         False      35m
kube-storage-version-migrator              4.13.13   True        False         False      40m
machine-api                                4.13.13   True        False         False      38m
machine-approver                           4.13.13   True        False         False      38m
machine-config                             4.13.13   True        False         False      38m
marketplace                                4.13.13   True        False         False      38m
monitoring                                 4.13.13   True        False         False      21m
network                                    4.13.13   True        False         False      39m
node-tuning                                4.13.13   True        False         False      38m
openshift-apiserver                        4.13.13   True        False         False      31m
openshift-controller-manager               4.13.13   True        False         False      33m
openshift-samples                          4.13.13   True        False         False      27m
operator-lifecycle-manager                 4.13.13   True        False         False      39m
operator-lifecycle-manager-catalog         4.13.13   True        False         False      39m
operator-lifecycle-manager-packageserver   4.13.13   True        False         False      33m
service-ca                                 4.13.13   True        False         False      39m
storage                                    4.13.13   True        False         False      40m
```

Disconnected cluster- verification check:
```
[root@rdr-shu-dis-lon06-bastion-0 ~]# oc get proxy -o yaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Proxy
  metadata:
    creationTimestamp: "2023-09-29T05:57:23Z"
    generation: 1
    name: cluster
    resourceVersion: "530"
    uid: 706ce68e-d725-45f3-a7cf-8ecbf8652936
  spec:
    trustedCA:
      name: ""
  status: {}
kind: List
metadata:
  resourceVersion: ""
```

Few pods show error in pinging and pulling images from registry.redhat.io repo, as the cluster is disconnected.
```
[root@rdr-shu-dis-lon06-bastion-0 ~]#  oc get pods -A | grep -v "Running\|Completed"
NAMESPACE                                          NAME                                                                READY   STATUS             RESTARTS      AGE
openshift-marketplace                              certified-operators-rwmb4                                           0/1     ImagePullBackOff   0             30m
openshift-marketplace                              certified-operators-v27sp                                           0/1     ImagePullBackOff   0             41m
openshift-marketplace                              community-operators-8w4bt                                           0/1     ImagePullBackOff   0             41m
openshift-marketplace                              community-operators-rr7rx                                           0/1     ImagePullBackOff   0             30m
openshift-marketplace                              redhat-marketplace-95lqv                                            0/1     ImagePullBackOff   0             30m
openshift-marketplace                              redhat-marketplace-bh2th                                            0/1     ImagePullBackOff   0             41m
openshift-marketplace                              redhat-operators-cqtkv                                              0/1     ImagePullBackOff   0             30m
openshift-marketplace                              redhat-operators-v8hm7                                              0/1     ImagePullBackOff   0             41m
powervm-rmc                                        powervm-rmc-4z6wk                                                   0/1     ImagePullBackOff   0             17m
powervm-rmc                                        powervm-rmc-8thrj                                                   0/1     ImagePullBackOff   0             17m
powervm-rmc                                        powervm-rmc-kpq28                                                   0/1     ImagePullBackOff   0             17m
powervm-rmc                                        powervm-rmc-l2z4w                                                   0/1     ImagePullBackOff   0             17m
powervm-rmc                                        powervm-rmc-v9t88                                                   0/1     ImagePullBackOff   0             17m


[root@rdr-shu-dis-lon06-bastion-0 ~]# oc describe pod certified-operators-rwmb4 -n openshift-marketplace
Name:                 certified-operators-rwmb4
Namespace:            openshift-marketplace
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      certified-operators
Node:                 lon06-master-0.rdr-shu-dis.ibm.com/193.168.200.77
Start Time:           Fri, 29 Sep 2023 02:23:32 -0400
Labels:               catalogsource.operators.coreos.com/update=certified-operators
                      olm.catalogSource=
                      olm.pod-spec-hash=5c8bf767c8
Annotations:          cluster-autoscaler.kubernetes.io/safe-to-evict: true
                      k8s.ovn.org/pod-networks:
                        {"default":{"ip_addresses":["10.128.0.14/23"],"mac_address":"0a:58:0a:80:00:0e","gateway_ips":["10.128.0.1"],"ip_address":"10.128.0.14/23"...
                      k8s.v1.cni.cncf.io/network-status:
                        [{
                            "name": "ovn-kubernetes",
                            "interface": "eth0",
                            "ips": [
                                "10.128.0.14"
                            ],
                            "mac": "0a:58:0a:80:00:0e",
                            "default": true,
                            "dns": {}
                        }]
                      openshift.io/scc: restricted-v2
                      operatorframework.io/managed-by: marketplace-operator
                      seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:               Pending
IP:                   10.128.0.14
IPs:
  IP:  10.128.0.14
Containers:
  registry-server:
    Container ID:
    Image:          registry.redhat.io/redhat/certified-operator-index:v4.13
    Image ID:
    Port:           50051/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        10m
      memory:     50Mi
    Liveness:     exec [grpc_health_probe -addr=:50051] delay=10s timeout=5s period=10s #success=1 #failure=3
    Readiness:    exec [grpc_health_probe -addr=:50051] delay=5s timeout=5s period=10s #success=1 #failure=3
    Startup:      exec [grpc_health_probe -addr=:50051] delay=0s timeout=5s period=10s #success=1 #failure=10
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gnzzb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-gnzzb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
                             node-role.kubernetes.io/master=
Tolerations:                 node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 120s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 120s
Events:
  Type     Reason          Age                 From               Message
  ----     ------          ----                ----               -------
  Normal   Scheduled       30m                 default-scheduler  Successfully assigned openshift-marketplace/certified-operators-rwmb4 to lon06-master-0.rdr-shu-dis.ibm.com
  Normal   AddedInterface  30m                 multus             Add eth0 [10.128.0.14/23] from ovn-kubernetes
  Normal   Pulling         26m (x4 over 30m)   kubelet            Pulling image "registry.redhat.io/redhat/certified-operator-index:v4.13"
  Warning  Failed          25m (x4 over 29m)   kubelet            Failed to pull image "registry.redhat.io/redhat/certified-operator-index:v4.13": rpc error: code = DeadlineExceeded desc = pinging container registry registry.redhat.io: Get "https://registry.redhat.io/v2/": dial tcp 2.16.57.215:443: i/o timeout
  Warning  Failed          25m (x4 over 29m)   kubelet            Error: ErrImagePull
  Warning  Failed          24m (x7 over 29m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff         43s (x89 over 29m)  kubelet            Back-off pulling image "registry.redhat.io/redhat/certified-operator-index:v4.13"
```

Local registry is configured:
```
[root@rdr-shu-dis-lon06-bastion-0 ~]# podman ps -a
CONTAINER ID  IMAGE                                      COMMAND               CREATED            STATUS            PORTS                   NAMES
4317df3069cf  docker.io/ibmcom/registry-ppc64le:2.6.2.5  serve /etc/docker...  About an hour ago  Up About an hour  0.0.0.0:5000->5000/tcp  local-registry
```
Automation used - https://github.com/ocp-power-automation/ocp4-playbooks/pull/176

One change needed in automation:
ocp4-playbooks/playbooks/roles/ocp-upgrade/tasks/restricted_network_upgrade.yaml
At line number 44 replace `.yaml` to `.json`

```
[root@rdr-shu-dis-lon06-bastion-0 ocp4-playbooks]# cat log01.txt

PLAY [Upgrade OCP cluster] *****************************************************

TASK [Gathering Facts] *********************************************************
ok: [rdr-shu-dis-lon06-bastion-0]

TASK [include_role : ocp-upgrade] **********************************************

TASK [Check if cluster operators and nodes are healthy] ************************

TASK [cluster-health-check : Check all co are in 'Available' state and not in 'Progressing' or 'Degraded' state] ***
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [cluster-health-check : Check all node are healthy] ***********************
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [cluster-health-check : Fail incase cluster state is unhealthy] ***********
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Set upgrade channel] ***************************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Upgrade cluster] *******************************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Waiting until upgrade completes] ***************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Check for upgrade completion] ******************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Upgrade cluster] *******************************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Waiting until upgrade completes] ***************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Check for upgrade completion] ******************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : EUS to EUS upgrades] ***************************************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Update restricted network ocp cluster] *********************
included: /root/ocp4-playbooks/playbooks/roles/ocp-upgrade/tasks/restricted_network_upgrade.yaml for rdr-shu-dis-lon06-bastion-0

TASK [ocp-upgrade : Get count of paused machine config pools] ******************
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Warn if machine config pools are paused] *******************
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Set ocp image url] *****************************************
ok: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : set image directory] ***************************************
ok: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Create repo image directory] *******************************
ok: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Mirror images and configuration manifests to a directory] ***
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Get sha key of the image] **********************************
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Upload images to local container registry] *****************
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Apply mirrored release image signature config] *************
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Get the OCP version] ***************************************
ok: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Providing the administrator acknowledgement for 4.8 to 4.9 upgrades] ***
skipping: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Upgrade ocp using a release image from local repository] ***
changed: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Waiting until upgrade completes] ***************************
Pausing for 5400 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [rdr-shu-dis-lon06-bastion-0]

TASK [ocp-upgrade : Check for upgrade completion] ******************************
changed: [rdr-shu-dis-lon06-bastion-0]

PLAY RECAP *********************************************************************
rdr-shu-dis-lon06-bastion-0 : ok=16   changed=9    unreachable=0    failed=0    skipped=11   rescued=0    ignored=0
```
Note: Playbook run Successful but cluster is not upgraded
```
[root@rdr-shu-dis-lon06-bastion-0 ~]# oc version
Client Version: 4.13.13
Kustomize Version: v4.5.7
Server Version: 4.13.13
Kubernetes Version: v1.26.7+c7ee51f

[root@rdr-shu-dis-lon06-bastion-0 ~]# oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.13   True        False         7h26m   Cluster version is 4.13.13

[root@rdr-shu-dis-lon06-bastion-0 ~]# oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.13.13   True        False         False      6h59m
baremetal                                  4.13.13   True        False         False      7h23m
cloud-controller-manager                   4.13.13   True        False         False      7h25m
cloud-credential                           4.13.13   True        False         False      7h35m
cluster-autoscaler                         4.13.13   True        False         False      7h22m
config-operator                            4.13.13   True        False         False      7h23m
console                                    4.13.13   True        False         False      7h4m
control-plane-machine-set                  4.13.13   True        False         False      7h22m
csi-snapshot-controller                    4.13.13   True        False         False      7h23m
dns                                        4.13.13   True        False         False      7h22m
etcd                                       4.13.13   True        False         False      7h21m
image-registry                             4.13.13   True        False         False      6h58m
ingress                                    4.13.13   True        False         False      7h8m
insights                                   4.13.13   True        False         False      4h19m
kube-apiserver                             4.13.13   True        False         False      7h15m
kube-controller-manager                    4.13.13   True        False         False      7h20m
kube-scheduler                             4.13.13   True        False         False      7h19m
kube-storage-version-migrator              4.13.13   True        False         False      7h23m
machine-api                                4.13.13   True        False         False      7h22m
machine-approver                           4.13.13   True        False         False      7h22m
machine-config                             4.13.13   True        False         False      7h22m
marketplace                                4.13.13   True        False         False      7h22m
monitoring                                 4.13.13   True        False         False      7h5m
network                                    4.13.13   True        False         False      7h23m
node-tuning                                4.13.13   True        False         False      7h22m
openshift-apiserver                        4.13.13   True        False         False      7h15m
openshift-controller-manager               4.13.13   True        False         False      7h17m
openshift-samples                          4.13.13   True        False         False      7h11m
operator-lifecycle-manager                 4.13.13   True        False         False      7h23m
operator-lifecycle-manager-catalog         4.13.13   True        False         False      7h23m
operator-lifecycle-manager-packageserver   4.13.13   True        False         False      7h17m
service-ca                                 4.13.13   True        False         False      7h23m
storage                                    4.13.13   True        False         False      7h24m
```

**var file:**
```
examples/upgrade_vars.yaml
---
eus_upgrade_version: ""  
eus_upgrade_channel: ""  
eus_upgrade_image: ""    
eus_upstream: ""         
upgrade_version: "4.14.0-rc.2"  
upgrade_channel: ""  
upgrade_image: "quay.io/openshift-release-dev/ocp-release:4.14.0-rc.2-ppc64le"    
pause_time: 90     
delay_time: 600    


playbooks/roles/ocp-upgrade/defaults/main.yaml
---
eus_upgrade_version: ""
eus_upgrade_channel: ""
eus_upgrade_image: ""
eus_upstream: ""
upgrade_version: "4.14.0-rc.2"
upgrade_channel: ""
upgrade_image: "quay.io/openshift-release-dev/ocp-release:4.14.0-rc.2-ppc64le"
pause_time: 90
delay_time: 600
restricted_network_upgrade: true
architecture: "ppc64le"
local_secret: "/root/.openshift/pull-secret-updated"
local_registry: "registry.rdr-shu-dis.ibm.com:5000"
local_repository: "ocp4/openshift4"
```

Command use to run the playbook: ansible-playbook -i inventory -e @examples/upgrade_vars.yaml playbooks/upgrade.yaml | tee log.txt

### PR DESCRIPTION
**Pull request by sajauddin**
Adding code to add admin ack for 4.13 to 4.14 upgrades for both EUS as well as restricted upgrade

### CODE REVIEW

**Review by yussufsh — APPROVED** [review]
/lgtm
However, I think we should add this in terraform var.tfvars doc or give the user some kind of warning.

**Comment by yussufsh** [comment]
@Rajalakshmi-Girish @mkumatag I see the bot is not removing the label `[do-not-merge/non-mergeable]` when lgtm is added. Seen this somewhere else as well. If I remove the label manually it gets merged. Kindly check.

**Comment by mkumatag** [comment]
> @Rajalakshmi-Girish @mkumatag I see the bot is not removing the label `[do-not-merge/non-mergeable]` when lgtm is added. Seen this somewhere else as well. If I remove the label manually it gets merged. Kindly check.

this is because of the following reason, need to find why it is really blocked?

image

**Comment by mkumatag** [comment]
because commit is not signed!

**Comment by yussufsh** [comment]
> because commit is not signed!

I see the DCO check as green 🤔 
```
All commits are signed off!
```

**Comment by yussufsh** [comment]
I think the commits are signed but unverified. I have removed the strict branch rule. Thanks for letting me know @mkumatag .

**Pull request merged**
