### PR TITLE
registry fix

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot Parab <prajot.parab@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
Can you describe the bug you are trying to solve? An issue with details will help understand the problem and the fix.

**Comment by Prajyot-Parab** [comment]
Fixes: #104

**Review by bpradipt — COMMENTED** [review]
@Prajyot-Parab should there be a systemd drop-in file for automatic restart of registry service ? Or am I missing something ?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab should there be a systemd drop-in file for automatic restart of registry service ? Or am I missing something ?

That is already configured,  just that in this case the registry remains in a UP state but becomes unresponsive so these changes are needed.

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
lgtm

**Pull request merged**
