### PR TITLE
Add access to non-root users

### PR DESCRIPTION
**Pull request by aishwaryabk**
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — DISMISSED** [review]
/lgtm

**Comment by aishwaryabk** [comment]
Updated changes for ocp-ha.

**Review by yussufsh — APPROVED** [review]
lgtm

**Review by Prajyot-Parab — APPROVED** [review]
/approve

**Pull request merged**
