### PR TITLE
Support bastion HA

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by bpradipt** [comment]
@yussufsh this overall looks good. Do you mind adding a doc explaining the HA topology and the approach. This will be handy going forward

**Review by Prajyot-Parab — DISMISSED** [review]
/lgtm

**Comment by yussufsh** [comment]
> @yussufsh this overall looks good. Do you mind adding a doc explaining the HA topology and the approach. This will be handy going forward

I have added some information in README. This is only using HA setup to complete the openshift install, cannot define the complete topology here.

**Review by bpradipt — COMMENTED** [review]
/lgtm
Thanks @yussufsh

**Review by bpradipt — DISMISSED** [review]

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by bpradipt — APPROVED** [review]

**Pull request merged**
