### PR TITLE
Fix NACK problem on shared network,  Fix #137

### LINKED ISSUE #137: OCP DHCP does not work nice with network with exist DHCP
Even OCP DHCP already configured with only provide the IPs to MAC defined dhcpd.conf, it will send out NACK to others, that cause network problem. We need to comment out `authoritative;` to avoid to send out NACK to keep silence.

### PR DESCRIPTION
**Pull request by cs-zhang**
Fixed: #137 

Signed-off-by: CS Zhang <zhangcho@us.ibm.com>

### CODE REVIEW

**Review by yussufsh — APPROVED** [review]
/lgtm

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
@cs-zhang the bot is not enabled for this project. You will need to cherry pick and create PR manually.

**Comment by mkumatag** [comment]
> @cs-zhang the bot is not enabled for this project. You will need to cherry pick and create PR manually.

why don't we enable! @yussufsh do you have PR handy we used for other repo which @cs-zhang can use.

**Comment by mkumatag** [comment]
> > @cs-zhang the bot is not enabled for this project. You will need to cherry pick and create PR manually.
> 
> why don't we enable! @yussufsh do you have PR handy we used for other repo which @cs-zhang can use.

I see this repo itself is not configured to use prow :) @Rajalakshmi-Girish can you please add web hook and submit all the required changed to the test-infra to work with this repo like https://github.com/ocp-power-automation/ocp4-upi-powervs repo?

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish lets create the owner file, we can copy from the https://github.com/ocp-power-automation/ocp4-upi-powervs project.

**Pull request merged**
