### PR TITLE
Split the install playbooks for sequential execution

### LINKED ISSUE #170: Not possible to run playbooks sequentially
We different playbook levels to run them sequentially to avoid the rhcos node going into emergency shell due to failed ignition.

1. Create OCP configurations and ignition files
2. Check and configure bootstrap node
3. Check and configure control-plane nodes and wait for bootstrap-complete step
4. Check and configure compute nodes, wait for install-complete step and run post-install steps
5. Upgrade OCP cluster

### PR DESCRIPTION
**Pull request by yussufsh**
This is needed for required components to wait for previous component to complete, otherwise the rhcos node may go into emergency shell and a reboot is needed to retry the ignition process.

Fixes #170

Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by Rajalakshmi-Girish** [comment]
@yussufsh: PR is not mergeable.

<details>

The PR state is: BLOCKED

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mkumatag** [comment]
> @yussufsh: PR is not mergeable.
> 
> <details>
> 
> The PR state is: BLOCKED
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
> </details>

@Rajalakshmi-Girish can you please shutdown all the prow instances with your personal key if you are running somewhere..

**Pull request merged**
